[general]
email = "giteshsorout@gmail.com"

[openrouter]
api_key = "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"       # ✅ Double quotes
base_url = "https://openrouter.ai/api/v1"   # ✅ Double quotes
