[general]
email = "giteshsorout@gmail.com"

[openrouter]
api_key = "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"       # ✅ Double quotes
base_url = "https://openrouter.ai/api/v1"   # ✅ Double quotes
